# commit to be tagged for the new release
commit = "HEAD"

project_name = "Omni"
github_repo = "siderolabs/omni"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

pre_release = false
previous = "v0.50.0"

[notes]

[notes.config-file]
description = """\
Omni can now be configured using `YAML` configuration file in addition to the command line flags.
The parameter `--config-file` can be used for that. Any command line flags have higher priority.
"""
